# Generated by Django 5.1.3 on 2025-01-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('items', models.TextField(verbose_name='Товары')),
                ('quantities', models.TextField(verbose_name='Количество каждого товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
        ),
    ]
